shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-romaji-complete]
github = "aoyama-val/zsh-romaji-complete"
apply = ["fpath", "source"]

[plugins.ni]
github = "azu/ni.zsh"